### ISSUE TITLE
Plugin throwing error in 2.7.1-1

### ISSUE THREAD

**Issue by fellenberger** [ikogan/rundeck-http-plugin#4]
After upgrade to Rundeck 2.7.1-1, all of my http plugin jobs are failing.  They were working fine prior to upgrade to 2.7.1-1.  After enabling debug for a job exec, I am seeing the error below.  I made sure that  rundeck-http-plugin-1.0.4.jar is present in the newly generated libext folder, so not exactly sure why a NoClassDefFoundError is being thrown.  Is this a compatibility issue?

[workflow] Begin execution: node-first context: null
[workflow] Begin step: 1,edu.ohio.ais.rundeck.HttpWorkflowStepPlugin
1: Workflow step executing: StepExecutionItem{type='edu.ohio.ais.rundeck.HttpWorkflowStepPlugin', keepgoingOnSuccess=false, hasFailureHandler=false}
Failed executing step plugin [edu.ohio.ais.rundeck.HttpWorkflowStepPlugin]: java.lang.NoClassDefFoundError: com/dtolabs/client/utils/HttpClientException	at edu.ohio.ais.rundeck.HttpWorkflowStepPlugin.doRequest(HttpWorkflowStepPlugin.java:191)
	at edu.ohio.ais.rundeck.HttpWorkflowStepPlugin.executeStep(HttpWorkflowStepPlugin.java:357)
	at com.dtolabs.rundeck.core.execution.workflow.steps.StepPluginAdapter.executeWorkflowStep(StepPluginAdapter.java:97)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:85)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:360)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:732)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowItemsForNodeSet(BaseWorkflowExecutor.java:419)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWFSection(NodeFirstWorkflowExecutor.java:313)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:119)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:317)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
Caused by: java.lang.ClassNotFoundException: com.dtolabs.client.utils.HttpClientException

**Comment by ikogan** [comment]
This is now fixed in https://github.com/ohioit/rundeck-http-plugin/commit/dc74b26318d8bf8a0971771554bb4020b647b7e8. Version 1.0.5 with this fix has been released in https://github.com/ohioit/rundeck-http-plugin/releases/tag/1.0.5.

**Comment by fellenberger** [comment]
Confirming that my tests using v1.0.5 of the http plugin in Rundeck 2.7.2-1 succeeded.  Thanks for the quick turnaround.
